# Generated by Django 5.2.7 on 2025-11-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_alter_conference_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
