# Generated by Django 5.2.7 on 2025-11-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0004_rename_update_at_conference_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
